<?php
/**
 * Copyright 2016 Henrik Hedelund
 *
 * This file is part of Henhed_Piwik.
 *
 * Henhed_Piwik is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Henhed_Piwik is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Henhed_Piwik.  If not, see <http://www.gnu.org/licenses/>.
 */

?>
<?php /* @var $block \Henhed\Piwik\Block\Adminhtml\Report\Dashboard */ ?>
<iframe src="<?php echo $block->getIframeUrl(); ?>"
        frameborder="0"
        marginheight="0"
        marginwidth="0"
        width="100%"
        height="2048px"
        scrolling="no"
        seamless="seamless"
        style="overflow: hidden;">
</iframe>
